name: Update Images

on:
  workflow_dispatch:
    inputs:
      Operator_version:
        description: "Dynatrace Operator version tag"
        required: true
        type: string
      OneAgent_version:
        description: "Dynatrace OneAgent version tag"
        required: true
        type: string
  push:
    branches:
      - master

jobs:
  display:
    name: "Display versions"
    runs-on: ubuntu-latest
    steps:
      - name: "Display Operator version"
        run: |
          echo "Operator Version: ${{ inputs.Operator_version }}"
          echo "Image: public.ecr.aws/dynatrace/dynatrace-operator:${{ inputs.Operator_version }}"

      - name: "Display OneAgent version"
        run: |
          echo "OneAgent Version: ${{ inputs.OneAgent_version }}"
          echo "Image: public.ecr.aws/dynatrace/dynatrace-oneagent:${{ inputs.OneAgent_version }}"
